### ISSUE TITLE
Can't create a column with a single String value

### ISSUE THREAD

**Issue by devcrocod** [nikitinas/dataframe#13]
Following code:
```
val name by column("Alice")
```
throws an exception because of [column](https://github.com/nikitinas/dataframe/blob/860d3a115058cf28a971bd0db5a850087e1b09e6/src/main/kotlin/org/jetbrains/dataframe/Columns.kt#L90) method.

**Comment by nikitinas** [comment]
New API:
`val name by columnOf("Alice")`
