### ISSUE TITLE
Columns are in a different order

### ISSUE THREAD

**Issue by devcrocod** [nikitinas/dataframe#14]
```
data class Person(val name: String, val age: Int)
val persons = listOf(Person("Alice", 20), Person("Bob", 23))
persons.toDataFrame()
```

actual:
| age        | name   |
| -------- |:-------:|
| 20      | Alice |
| 23      | Bob  |

expected:
| name        | age   |
| -------- |:-------:|
| Alice      | 20 |
| Bob      | 23  |

**Comment by nikitinas** [comment]
Can't be fixed because there is no way to get declared order of properties at runtime
