### ISSUE TITLE
Display more then 20 DataFrame rows in Kotlin Jupyter

### ISSUE THREAD

**Issue by UnlikeMars** [nikitinas/dataframe#21]
When using `take(n)`, `takeLast(n)` or `head(n)` with values `n > 20`, rows larger than 20 will always be truncated.

Displayed tables are showing a limit of 20 rows with the note `... only showing top 20 of 25 rows`.

Is it possible to configure this library to display more than 20 rows in Kotlin Jupyter?

**Comment by ileasile** [comment]
Fixed in aforementioned PR. Usage:
```kotlin
data class Person(val age: Int, val name: String)
val df = (1..70).map { Person(it, "A".repeat(it)) }.toDataFrameByProperties()

dataFrameConfig.display.rowsLimit = 50
df
```
